### ISSUE TITLE
openstreetmap not displayed 

### ISSUE THREAD

**Issue by radioman1511** [microp11/iridiumlive#11]
openstreetmap not displayed on the website . i start the application with followed commands:
1 cd iridiumlive
2 cd IridiumLive
3 dotnet run 
Is that right?
grts radioman1511

**Comment by radioman1511** [comment]
![Bildschirmfoto vom 2019-12-19 15-54-43](https://user-images.githubusercontent.com/16371774/71183308-0f84c200-2278-11ea-84b8-bbdd5f7e8d7b.png)
Livemap

**Comment by microp11** [comment]
I assume this is your own compilation. I suspect the map component is missing. wwwroot. Download any zip I made and look into the wwwroot folder. Copy the "_content" folder in there as well.

**Comment by radioman1511** [comment]
i can not found "_content" folder "
i use "git clone https://github.com/microp11/iridiumlive.git"
and than 
1 cd iridiumlive
2 cd IridiumLive
3 dotnet run

**Comment by radioman1511** [comment]
excuse i am a newbie with .net and visualstudio

**Comment by microp11** [comment]
Download any zip I made and look into the wwwroot folder. Copy the "_content" folder in there as well.

**Comment by radioman1511** [comment]
thanks for information now it is running, merry christmas great job. grts radioman1511
