### ISSUE TITLE
Coordinates wrong value

### ISSUE THREAD

**Issue by radioman1511** [microp11/iridiumlive#12]
Now new problem coordinates are calculated incorrectly, e.g. 49.21N as 4921 N and 7.01 E as 701 E. Where is the mistake?grts radioman1511

**Comment by microp11** [comment]
Running the debugger on the webpage would have indicated the missing map resource in #11 . Running debugger on the server will show you how data gets passed from one side to another.
The binaries built from the same source and available for download display the coordinates properly. Download, run and verify. And then debug. Cheers!

**Comment by microp11** [comment]
Check your parser.

**Comment by radioman1511** [comment]
Under Debian 9  the program works not correctly(coordinates wrong), when i debugged with Kdbg what a wonder it is works fine and the marker is set correctly, i do not know what is the error. The parser works fine. grts radioman1511

**Comment by radioman1511** [comment]
@microp11 Under Debian 9 the program works not correctly(coordinates wrong), when i debugged with Kdbg what a wonder it is works fine and the marker is set correctly, i do not know what is the error. The parser works fine. grts radioman1511
