### ISSUE TITLE
Iridium live not displaying any information

### ISSUE THREAD

**Issue by alphapats** [microp11/iridiumlive#19]
I am using latest builds of iridium-live and iridium-toolkit. all changes were made to udp-for-il is running and sending data over udp. The same verified using wireshark. But, iridium-live is not showing any data. Anyone who knows the workaround?

**Comment by microp11** [comment]
I have just compiled this project from source in the free Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.1.0. It had compiled the solution with no issues at all. It is just a matter of debugging it and finding the issue

This is an open source project, any .net developer can fix this incompatibility it if they wish.
I will have to setup an iridium source to debug it and I do not want to promise a deadline.
Once fixed I will need a help to test it.

**Comment by microp11** [comment]
I have restored my old 2019 linux and with the above compiled app, all works well.
Will install latest gr-iridium and toolkit and will see what happens.

**Comment by alphafox02** [comment]
If you use this specific fork it works with newer gr-iridium/iridium toolkit

https://github.com/ereinitzhuber/iridiumlive/tree/fix-issue-%2318

Waiting to see if @microp11 generates a newer binary, else maybe I will try to build a binary based on the fork mentioned above. I've tested the fork on a Pi4 with newer iridium, myself and others have found it to work.

**Comment by microp11** [comment]
I understand the idea, pretty smart. I will setup a gr-iridium tomorrow on my RPi and give it a try. Could you please indicate which gnuradio version I would need and which gr-iridium, as latest gnuradio is 3.10 I think.

**Comment by microp11** [comment]
Found the other #18 issue and the link to https://sourceforge.net/projects/dragonos-pi64/
Will install gr-iridium on it as well and the kit.
Do I need a specific branch for gr-iridium?

**Comment by alphafox02** [comment]
I’m using 3.8 for gnuradio so I don’t know if there’s a difference. I just got it all built and messing with it now before bed. I made sure to use his “fix issue 18” branch.

**Comment by alphafox02** [comment]
Here’s more info. The version of gr-Iridium and the toolkit I put in the Pi64 build will send ring alerts to the fork of IridiumLive. 

Now here’s what’s interesting. I put the latest gr-iridium (3.8 branch) and toolkit on my laptop with the fork of IridiumLive and with this configuration no ring alerts are seen even by the fork of IridiumLive. So by a process of elimination, I first used the iridium-toolkit pulled from the Pi and used it with the new gr-iridium. Still nothing in the fork of IridiumLive. I then used the gr-iridium version from the pi rebuilt for x64. I then received ring alerts again. 

Edit: I tried the other way around as well. I think something additional has changed in the newest gr-iridium (3.8) and newer toolkit that’s preventing even the fork from getting ring alerts or maybe something is wrong on gr-iridium/toolkit side.

**Comment by alphafox02** [comment]
> Found the other #18 issue and the link to https://sourceforge.net/projects/dragonos-pi64/
> Will install gr-iridium on it as well and the kit.
> Do I need a specific branch for gr-iridium?

I can’t remember if I answered, but everything is already installed on the Pi image. Look in /usr/src and you’ll see everything to include the IridiumLive fork.

**Comment by microp11** [comment]
Hi @amitpathania , @alphafox02, I will close this issue and move the discussion to #18 .
If you get to this point, just follow on the #18
